# Generated by Django 5.1.4 on 2024-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус транзакции'),
        ),
    ]
